### ISSUE TITLE
Travis vs Jenkins

### ISSUE THREAD

**Issue by tjanela** [SwiftCamp/SwiftCamp#4]
We use Jenkins for CI purposes.

Jenkins allows us to have a single point of maintenance for every type of project we currently develop and maintain.
Jenkins costs 0 in opex.
Jenkins is totally maintained and controlled by us and we have total flexibility in terms of configurations.

Using Travis results in we having to maintain/support two CI systems (Travis has beta support for C#).
Travis costs at least 129 USD in opex per month.
Travis is a hosted service. 

What is the main reason behind suggesting Travis? What is wrong with Jenkins?

**Comment by diogoAntunes** [comment]
For a corporate use I actually advice against Travis CI, for the same reasons you explained, but mostly for the fact that Jenkins allows for better control and customisation. 

But for a OSS project Travis CI is much more simple and faster to setup (and also free :moneybag:).

**Comment by tjanela** [comment]
OK to keep it simple here I do admit as well that mentioning Travis is best and simpler. This being an OSP I close my own question.
